language: python

python:
  - "3.6.7"

services:
  - docker

install:
  - pip3 install -r requirements.txt

before_install:
- docker pull eclipse-mosquitto
- docker run --rm --name=mqtt -d -p 1883:1883 -p 9001:9001 eclipse-mosquitto
- docker ps -a
- echo "MQTT_HOST='127.0.0.1'\nMQTT_PORT=1883\nMQTT_TOPIC='Lights'" > broker.env
# - export COVERALLS_REPO_TOKEN=$API_USERNAME

script:
  - flake8 homeAutomation
  - pytest --cov=homeAutomation --cov-report=html tests

after_success:
  - coveralls